# Generated by Django 4.2.2 on 2023-06-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Czytelnicy',
            fields=[
                ('id_czytelnika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_gatunku', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id_ksiazki', models.AutoField(primary_key=True, serialize=False)),
                ('tytul_ksiazki', models.CharField(max_length=100)),
                ('czytali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.czytelnicy')),
                ('gatunek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteka.gatunek')),
            ],
        ),
    ]
